// generated by scripts/export-idl.mjs — do not edit
export const VAULT_ERRORS: Record<number, { name: string; msg: string }> = {
  "6000": {
    "name": "Unauthorized",
    "msg": "Unauthorized"
  },
  "6001": {
    "name": "Paused",
    "msg": "Program is paused"
  },
  "6002": {
    "name": "ProtocolShareTooHigh",
    "msg": "Protocol share above the 20% cap"
  },
  "6003": {
    "name": "DisputeWindowTooLong",
    "msg": "Dispute window must be shorter than the minimum epoch length"
  },
  "6004": {
    "name": "BasketLength",
    "msg": "Basket must have 1 to 10 legs"
  },
  "6005": {
    "name": "MintNotAllowed",
    "msg": "Basket mint is not on the allowlist"
  },
  "6006": {
    "name": "DuplicateMint",
    "msg": "Duplicate basket mint"
  },
  "6007": {
    "name": "WeightsMustSum",
    "msg": "Basket weights must be non-zero and sum to 10000"
  },
  "6008": {
    "name": "EpochLengthTooShort",
    "msg": "Epoch length below the minimum"
  },
  "6009": {
    "name": "AlreadyBound",
    "msg": "Vault is already bound to a launch"
  },
  "6010": {
    "name": "NotBound",
    "msg": "Vault is not bound to a launch yet"
  },
  "6011": {
    "name": "NotPumpAccount",
    "msg": "Bonding curve account is not owned by the pump program"
  },
  "6012": {
    "name": "WrongBondingCurve",
    "msg": "Bonding curve does not belong to the expected mint"
  },
  "6013": {
    "name": "WrongCreator",
    "msg": "Launch creator is not this vault"
  },
  "6014": {
    "name": "NothingToHarvest",
    "msg": "Nothing to harvest"
  },
  "6015": {
    "name": "SwapInFlight",
    "msg": "A swap is already in flight"
  },
  "6016": {
    "name": "NoSwapInFlight",
    "msg": "No swap in flight"
  },
  "6017": {
    "name": "SettleNotInTransaction",
    "msg": "swap_begin must be followed by swap_settle in the same transaction"
  },
  "6018": {
    "name": "BadLeg",
    "msg": "Leg index out of range"
  },
  "6019": {
    "name": "NothingToSwap",
    "msg": "Leg has nothing pending to swap"
  },
  "6020": {
    "name": "InsufficientOutput",
    "msg": "Swap output below minimum"
  },
  "6021": {
    "name": "WrongLegAccount",
    "msg": "Basket account does not match the leg"
  },
  "6022": {
    "name": "PeriodMismatch",
    "msg": "Epoch period must start where the previous one ended"
  },
  "6023": {
    "name": "InvalidPeriod",
    "msg": "Invalid epoch period"
  },
  "6024": {
    "name": "LengthMismatch",
    "msg": "Length mismatch"
  },
  "6025": {
    "name": "InsufficientUnallocated",
    "msg": "Not enough unallocated tokens for this epoch"
  },
  "6026": {
    "name": "EpochNotOpen",
    "msg": "Epoch is not open"
  },
  "6027": {
    "name": "EpochNotCancellable",
    "msg": "Only the latest epoch can be cancelled, and only before it becomes claimable"
  },
  "6028": {
    "name": "EpochNotExpirable",
    "msg": "Epoch claim window has not closed yet"
  },
  "6029": {
    "name": "EpochNotClaimable",
    "msg": "Epoch is not claimable yet"
  },
  "6030": {
    "name": "InvalidProof",
    "msg": "Invalid Merkle proof"
  },
  "6031": {
    "name": "EpochOverclaim",
    "msg": "Claim exceeds the epoch's declared amount for this token"
  },
  "6032": {
    "name": "NothingPending",
    "msg": "Nothing pending for this account and mint"
  },
  "6033": {
    "name": "TokenNotRescuable",
    "msg": "Basket and quote balances can never be rescued"
  },
  "6034": {
    "name": "Overflow",
    "msg": "Arithmetic overflow"
  }
};
