"use client";
import {useState} from "react";
import {useNews} from "@/lib/hooks/useNews";
import {NEWS_CATEGORIES,type NewsCategory} from "@/lib/news/types";
import {ArrowUpRight,ArrowsClockwise} from "@/components/ui/icons";
import {StateMessage} from "@/components/linkr/landing";
import {StoryArt} from "@/components/linkr/hero";
import {MotionSurface} from "@/components/linkr/motion";
export function NewsWire(){
 const[category,setCategory]=useState<NewsCategory|"all">("all");const[query,setQuery]=useState("");const[selected,setSelected]=useState<string|null>(null);
 const news=useNews({limit:60});const all=news.data?.preview?[]:news.data?.data?.items??[];
 const items=all.filter(i=>(category==="all"||i.category===category)&&(i.title+" "+i.source.name+" "+i.tickers.join(" ")).toLowerCase().includes(query.toLowerCase()));
 const item=items.find(i=>i.id===selected)??items[0];
 return <MotionSurface className="lk-news"><header className="lk-news-head"><span className="eyebrow">THE LINKR NEWSWIRE</span><h1>Read the signal.<br/><em>Find the connection.</em></h1><p>Reporting from the world. Context for your next thesis.</p></header><div className="lk-news-toolbar"><div className="segmented" role="group" aria-label="News categories">{[{id:"all" as const,label:"All stories"},...NEWS_CATEGORIES.filter(c=>all.some(i=>i.category===c.id))].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div><input type="search" aria-label="Search news" placeholder="Search headlines, sources or tickers" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="data-note">{news.isLoading?"Connecting to sources…":news.data?.stale?"Showing the last available reports.":news.data?.error?"Some news sources are unavailable.":`${all.length} reports from public sources`} <button className="text-action" aria-label="Refresh news" onClick={()=>news.refetch()}><ArrowsClockwise size={14}/></button></p>
 {items.length?<div className="lk-news-layout"><div className="lk-news-list" aria-label="Headlines">{items.map(i=><button key={i.id} aria-pressed={item?.id===i.id} onClick={()=>setSelected(i.id)}><small>{i.source.name} · {new Date(i.publishedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small><h3>{i.title}</h3><div className="stock-tags">{i.tickers.slice(0,4).map(t=><span key={t}>{t}</span>)}</div></button>)}</div>{item&&<article className="lk-news-detail glass"><StoryArt item={item}/><div className="lk-news-detail-body"><span className="eyebrow">{item.source.name}</span><h2>{item.title}</h2><time dateTime={item.publishedAt}>{new Date(item.publishedAt).toLocaleString("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"UTC"})} UTC</time><div className="stock-tags">{item.tickers.map(t=><span key={t}>{t}</span>)}</div><p>{item.summary??"Read the full report at the original source for the complete story."}</p>{item.url&&<a href={item.url} target="_blank" rel="noreferrer" className="lk-button primary">Read original report <ArrowUpRight size={17}/></a>}</div></article>}</div>:<StateMessage title={news.isLoading?"Connecting the dots…":all.length?"No matching stories.":"The newswire is reconnecting."} body={all.length?"Try another category or search term.":"Reports will appear here as soon as a source responds."} retry={()=>news.refetch()}/>}</MotionSurface>;
}
