"use client";
import Link from "next/link";
import {useState} from "react";
import {useNews} from "@/lib/hooks/useNews";
import {useVaults,useVaultConfig,useVaultEpochs} from "@/lib/hooks/useApi";
import {ArrowRight,ArrowUpRight,X} from "@/components/ui/icons";
import {RewardRibbon} from "@/components/launch/reward-ribbon";
import {TokenIcon} from "@/components/token-icon";
import {withAdded,withRemoved,evenWeights} from "@/lib/launch/options";
import type {TokenJson} from "@/lib/api-types";
import {MotionSurface,SignalLines} from "./motion";
import {Hero,StoryArt} from "./reference-hero";
import {ConnectionEngine} from "./connection-engine";
import {MarketChart} from "./chart";
import {explorerTxUrl} from "@/lib/solana/cluster";
import {usdOf} from "@/lib/format";
import {MarketGallery,StateMessage} from "./market-gallery";
export {MarketGallery,StateMessage};
const colors=["#0769ff","#6099f4","#98bbec","#ff952a","#446eac","#b1c6e4"];
export function BasketComposer(){
 const config=useVaultConfig();const[basket,setBasket]=useState<{token:TokenJson;weight:number}[]>([]);const[query,setQuery]=useState("");const assets=config.data?.basketTokens??[];const filtered=assets.filter(t=>(t.symbol+" "+t.name).toLowerCase().includes(query.toLowerCase()));
 const href="/launch?basket="+encodeURIComponent(JSON.stringify(basket.map(b=>({mint:b.token.mint,weight:b.weight}))));
 return <MotionSurface className="lk-section composer-section" id="composer"><div className="section-heading"><div><span className="eyebrow">03 / BUILD THE CONNECTION</span><h2>Your conviction.<br/><em>Your combination.</em></h2></div><p>Choose the stocks your holders receive.<br/>Give every part of the idea its place.</p></div><div className="composer-glass glass"><div className="composer-top"><span>Reward composition</span><strong>{basket.length? "100% connected":"Start with a stock"}</strong></div><RewardRibbon items={basket.map((b,i)=>({key:b.token.mint,label:b.token.symbol,weight:b.weight,color:colors[i%colors.length],mark:<TokenIcon symbol={b.token.symbol} address={b.token.mint} logoUrl={b.token.logoUrl} size={30}/>}))} onBalance={(k,a,b)=>setBasket(prev=>prev.map((v,i)=>i===k?{...v,weight:a}:i===k+1?{...v,weight:b}:v))} onRemove={mint=>setBasket(p=>withRemoved(p,b=>b.token.mint===mint))}/>
 <div className="composer-selected">{basket.map(b=><span key={b.token.mint}>{b.token.symbol} <strong>{b.weight}%</strong><button aria-label={`Remove ${b.token.symbol}`} onClick={()=>setBasket(p=>withRemoved(p,v=>v.token.mint===b.token.mint))}><X size={13}/></button></span>)}{basket.length>1&&<button onClick={()=>setBasket(evenWeights)} className="text-action">Equal weights</button>}</div>
 <div className="composer-search"><label htmlFor="stock-search">Available reward assets <span>{assets.length?assets.length:"—"}</span></label><input id="stock-search" type="search" placeholder="Find a company or ticker" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="asset-shelf">{filtered.slice(0,24).map(t=><button disabled={basket.some(b=>b.token.mint===t.mint)||basket.length>=10} key={t.mint} onClick={()=>setBasket(p=>withAdded(p,{token:t,weight:0}))}><TokenIcon symbol={t.symbol} address={t.mint} logoUrl={t.logoUrl} size={25}/><span>{t.symbol}</span><small>+</small></button>)}</div>{!assets.length&&<p className="data-note">{config.isLoading?"Checking the supported stock list…":"The supported stock list is currently unavailable."}</p>}{assets.length>0&&!filtered.length&&<p className="data-note">No stocks match this search.</p>}<div className="composer-bottom"><span>Up to 10 assets · Weights fixed at launch</span>{basket.length?<Link className="lk-button primary" href={href}>Continue with this basket <ArrowRight size={17}/></Link>:<button className="lk-button primary" disabled>Select stocks to continue</button>}</div></div></MotionSurface>
}
function NewsPreview(){const news=useNews({limit:4});const items=news.data?.preview?[]:news.data?.data?.items??[];return <MotionSurface className="lk-section news-preview"><div className="section-heading"><div><span className="eyebrow">04 / SIGNAL, MEET CONTEXT</span><h2>The world moves.<br/><em>Stay connected.</em></h2></div><Link className="text-action" href="/news">Open the newswire <ArrowUpRight size={17}/></Link></div><div className="news-preview-grid">{items.slice(0,3).map(item=><a key={item.id} href={item.url??undefined} target="_blank" rel="noreferrer" className="news-preview-card glass"><StoryArt item={item}/><div><small>{item.source.name} · {new Date(item.publishedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small><h3>{item.title}</h3><span className="text-action">Read the story <ArrowUpRight size={16}/></span></div></a>)}</div>{!items.length&&<StateMessage title={news.isLoading?"Reading the wire…":"The wire is reconnecting."} body="Headlines appear here directly from news sources." retry={()=>news.refetch()}/>}</MotionSurface>}
export function PayoutProof(){const vaults=useVaults();const vault=vaults.data?.vaults?.find(v=>v.epochCount>0);const epochs=useVaultEpochs(vault?.address??null);const rows=(epochs.data?.epochs??[]).filter(e=>e.status==="published");const points=rows.flatMap(e=>{const values=e.tokens.map((t,i)=>usdOf(e.claimedTotals[i]??"0",t.decimals,t.priceUsd));return values.some(v=>v===null)?[]:[{t:e.periodEnd,priceUsd:values.reduce<number>((s,v)=>s+(v??0),0)}]});const receipt=rows.find(e=>e.publishedSignature);
 return <MotionSurface className="lk-section proof-section"><div><span className="eyebrow">05 / FOLLOW THE VALUE</span><h2>A clear view.<br/><em>Every step of the way.</em></h2><p>See fees arrive, stocks accumulate and rewards reach their holders. Follow the receipts behind every distribution.</p><Link href="/claims" className="text-action">Your rewards <ArrowRight size={17}/></Link></div><div className="proof-glass glass"><div className="feature-top"><span>DISTRIBUTION HISTORY</span><span>{vault?.launch?.symbol??"LINKR"}</span></div>{points.length>=2?<MarketChart points={points} label="Delivered stock · current USD value"/>:<StateMessage title="Every payout leaves a trail." body={vaults.error?"Distribution history is currently unavailable.":"Verified distributions will appear when the connected markets have paid holders."}/>}<div className="proof-bottom"><span>Time-weighted. Verifiable.</span>{receipt?.publishedSignature?<a href={explorerTxUrl(receipt.publishedSignature)} target="_blank" rel="noreferrer">View receipt <ArrowUpRight size={15}/></a>:<Link href="/vaults">Explore markets <ArrowUpRight size={15}/></Link>}</div></div></MotionSurface>
}
function FAQ(){const[open,setOpen]=useState<number|null>(0);const rows=[["What am I actually holding?","You hold a coin launched on StonkFun. Its market price is independent of the stock basket. LINKR converts received creator fees into tokenised stocks for eligible holders."],["How are rewards divided?","Each distribution uses your balance multiplied by the time you held during that period. More trading can generate more fees, but rewards are variable and are not guaranteed."],["Can I choose the stocks?","As a creator, you choose up to ten supported assets and their weights before launch. The basket and payout period are fixed when the market is created."],["What happens after I connect my wallet?","Your portfolio shows accumulating rewards, pending distributions and delivered stocks. Creating a market or requesting a delivery requires a separate wallet approval."]];return <MotionSurface className="lk-section faq-section"><div><span className="eyebrow">A LITTLE MORE CONTEXT</span><h2>Good questions.<br/><em>Clear answers.</em></h2></div><div className="faq-list">{rows.map(([q,a],i)=><div key={q} className={open===i?"open":""}><button aria-expanded={open===i} aria-controls={`faq-${i}`} onClick={()=>setOpen(open===i?null:i)}>{q}<span>{open===i?"−":"+"}</span></button><div id={`faq-${i}`} className="faq-answer" inert={open!==i}><p>{a}</p></div></div>)}</div></MotionSurface>}
export function Landing(){return <><Hero/><MarketGallery/><ConnectionEngine/><BasketComposer/><NewsPreview/><PayoutProof/><FAQ/><MotionSurface className="closing-section"><SignalLines/><span className="eyebrow">THE NEXT CONNECTION IS YOURS.</span><h2>Make your idea<br/><em>mean more.</em></h2><Link href="/launch" className="lk-button primary">Launch your LINKR <ArrowRight size={18}/></Link><p>A story worth holding. A connection worth making.</p></MotionSurface></>}
