#!/usr/bin/env node
// Copies the Anchor build artifacts (IDL + TS types) into the web app so the client, indexer and keeper
// share one source of truth. Run after every `anchor build`.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "solana", "target");
const out = join(root, "web", "lib", "solana", "idl");
mkdirSync(out, { recursive: true });

const idlPath = join(target, "idl", "causa_vault.json");
const idl = JSON.parse(readFileSync(idlPath, "utf8"));
copyFileSync(idlPath, join(out, "causa_vault.json"));
copyFileSync(join(target, "types", "causa_vault.ts"), join(out, "causa_vault.ts"));

const errors = Object.fromEntries((idl.errors ?? []).map((e) => [e.code, { name: e.name, msg: e.msg }]));
writeFileSync(
  join(out, "errors.ts"),
  `// generated by scripts/export-idl.mjs — do not edit\nexport const VAULT_ERRORS: Record<number, { name: string; msg: string }> = ${JSON.stringify(errors, null, 2)};\n`,
);

console.log(`exported ${idl.metadata?.name ?? "idl"} v${idl.metadata?.version ?? "?"} (${idl.instructions.length} instructions, ${idl.accounts.length} accounts, ${Object.keys(errors).length} errors) → web/lib/solana/idl`);
console.log(`program id: ${idl.address}`);
