/**
 * Design sample for the newswire.
 *
 * This is NOT reporting. It exists so the news surfaces can be laid out and reviewed
 * before a provider is wired up, and it is served only when NEWS_PREVIEW=1 (which is
 * the default in `next dev` and never in production). Every surface that renders it
 * carries a "Sample" badge, and no item links anywhere — `url` is null throughout, so
 * nothing here can be mistaken for a real article by a real outlet.
 */
import type { NewsItem } from "./types";

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const SAMPLE_NEWS: NewsItem[] = [
  {
    id: "sample-1",
    title: "Hyperscaler capex guidance lifted again as rack orders pull forward",
    summary:
      "Order books for accelerators, optics and power gear are being filled a quarter earlier than planned, spreading the same spend across very different suppliers.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Markets Desk", domain: null },
    publishedAt: minutesAgo(4),
    category: "stocks",
    tickers: ["NVDA", "AVGO", "SMCI"],
    narratives: ["ai-infra"],
    insight:
      "The capex is confirmed; which line item it lands in is not. Optics and power names bill on a different cycle to silicon, so a single-ticker expression of this thesis is a bet on timing as much as direction.",
    sentiment: "bullish",
    tags: ["Capex", "AI infrastructure"],
  },
  {
    id: "sample-2",
    title: "Foundry pricing holds into next cycle as advanced packaging stays sold out",
    summary: "Leading-edge capacity remains allocated, keeping tool makers and the foundries on divergent margin paths.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Wire", domain: null },
    publishedAt: minutesAgo(21),
    category: "stocks",
    tickers: ["TSM", "ASML", "MU"],
    narratives: ["fabs"],
    insight:
      "Packaging constraints reward the toolmakers before they reach the foundry's revenue line. The basket holds both ends of that lag instead of guessing which reports first.",
    sentiment: "neutral",
    tags: ["Supply chain", "Semis"],
  },
  {
    id: "sample-3",
    title: "Grid interconnect queues stretch again as datacentre demand outruns build-out",
    summary:
      "Utilities are quoting multi-year connection timelines, while small-modular developers remain pre-revenue.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Energy Report", domain: null },
    publishedAt: minutesAgo(48),
    category: "markets",
    tickers: ["CEG", "OKLO", "GEV"],
    narratives: ["nuclear"],
    insight:
      "The buyer is the same in both cases; the income statement is not. Utilities are selling interconnects today, reactor developers are selling a decade from now.",
    sentiment: "bullish",
    tags: ["Power", "Datacentres"],
  },
  {
    id: "sample-4",
    title: "Tokenised equity volumes on Solana set a new weekly high",
    summary: "Deeper stock pools tightened spreads across the most-traded tickers on the chain.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Chain Report", domain: null },
    publishedAt: minutesAgo(72),
    category: "chain",
    tickers: ["AAPL", "TSLA", "NVDA"],
    narratives: [],
    insight:
      "Deeper stock liquidity is what makes a stock-paired launch tradeable at all — the pair asset has to be able to absorb the exit.",
    sentiment: "bullish",
    tags: ["Liquidity", "Solana"],
  },
  {
    id: "sample-5",
    title: "Launchpad activity rotates toward stock-quoted pairs",
    summary: "A growing share of new coins are choosing a tokenised stock as their pair asset rather than the native token.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Protocol Notes", domain: null },
    publishedAt: minutesAgo(96),
    category: "protocol",
    tickers: ["COIN", "MSTR"],
    narratives: ["crypto"],
    insight:
      "Every one of those launches had to compress a thesis into exactly one ticker. That constraint is the demand LINKR's market formation answers.",
    sentiment: "neutral",
    tags: ["StonkFun", "Baskets"],
  },
  {
    id: "sample-6",
    title: "Quantum roadmaps diverge as error-correction milestones slip unevenly",
    summary: "Four architectures, four timelines, and no consensus on which physics gets there first.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Wire", domain: null },
    publishedAt: minutesAgo(140),
    category: "stocks",
    tickers: ["IONQ", "RGTI", "QBTS"],
    narratives: ["quantum"],
    insight: "The single-name version of this trade is a coin flip on hardware physics. The basket is the thesis without the flip.",
    sentiment: "neutral",
    tags: ["Quantum", "R&D"],
  },
  {
    id: "sample-7",
    title: "Crypto-linked equities track spot moves more tightly than treasuries",
    summary: "Exchange and treasury-company names are pricing the same underlying with very different betas.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Markets Desk", domain: null },
    publishedAt: minutesAgo(190),
    category: "crypto",
    tickers: ["COIN", "MSTR", "CRCL"],
    narratives: ["crypto"],
    insight: "Same exposure, different leverage. Holding the set removes the beta guess from the thesis.",
    sentiment: "neutral",
    tags: ["Beta", "Crypto equities"],
  },
  {
    id: "sample-8",
    title: "Dividend vaults route creator fees into stock payouts",
    summary: "Fees earned by a launch are harvested into its paired stocks and paid out to holders on a schedule.",
    url: null,
    imageUrl: null,
    source: { name: "Sample LINKR Notes", domain: null },
    publishedAt: minutesAgo(260),
    category: "company",
    tickers: [],
    narratives: [],
    insight: "A launch's fee stream becomes stock exposure for the people holding it, rather than a claim only the deployer can make.",
    sentiment: null,
    tags: ["Vaults", "Dividends"],
  },
  {
    id: "sample-9",
    title: "Defence and space names decouple from the broader tape",
    summary: "Programme awards are landing unevenly, widening the gap between prime contractors and launch providers.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Wire", domain: null },
    publishedAt: minutesAgo(320),
    category: "markets",
    tickers: ["RKLB", "AVAV"],
    narratives: ["space"],
    insight: "Award timing, not sector direction, is what separates these names this quarter.",
    sentiment: "neutral",
    tags: ["Defence", "Space"],
  },
  {
    id: "sample-10",
    title: "Memory pricing firms as AI server builds absorb supply",
    summary: "Contract prices moved up for a second consecutive period, with the effect reaching suppliers at different times.",
    url: null,
    imageUrl: null,
    source: { name: "Sample Wire", domain: null },
    publishedAt: minutesAgo(400),
    category: "stocks",
    tickers: ["MU", "AMD", "TSM"],
    narratives: ["fabs", "ai-infra"],
    insight: "The same tailwind reaches memory, logic and the foundry in three different quarters.",
    sentiment: "bullish",
    tags: ["Memory", "Pricing"],
  },
];
